MUTECTL_PAUSE   EQU 1
MUTECTL_UNPAUSE EQU 2

SFX_JUMP EQU 1

SONG_OVERWORLD_LEVEL       EQU 1
SONG_LOST_LEVEL            EQU 2
SONG_FINISHED_LEVEL        EQU 3
SONG_INVINCIBLE            EQU 4
SONG_LOW_ON_TIME           EQU 9
SONG_12                    EQU 12
SONG_15                    EQU 15
SONG_TREE_ZONE             EQU 16
SONG_TREE_ZONE_UNDERGROUND EQU 17
SONG_SPACE_ZONE_LEVEL      EQU 19
SONG_TREE_ZONE_LEVEL       EQU 20
SONG_LOTTERY               EQU 21
SONG_24                    EQU 24
SONG_SPACE_ZONE            EQU 28
NUM_SONGS                  EQU 43
