INCLUDE "gbhw.asm"
INCLUDE "constants/sprites.asm"
INCLUDE "constants/audio.asm"

; sDemoMode
DEMO_PLAYBACK  EQU $0F
DEMO_RECORDING EQU $F0

MODE_LOAD_TITLESCREEN     EQU 0
MODE_TITLESCREEN          EQU 1
MODE_LEVEL                EQU 4
MODE_PAUSED               EQU 8
MODE_11                   EQU 11
MODE_WORLD                EQU 12
MODE_LOAD_CREDITS         EQU 18
MODE_CREDITS              EQU 19
MODE_20                   EQU 20
MODE_LOAD_SAVEFILE_SELECT EQU 25
MODE_SAVEFILE_SELECT      EQU 26

; sMarioDirection
MARIO_DIRECTION_LEFT  EQU $FF
MARIO_DIRECTION_RIGHT EQU $01

LEVEL_INTRO     EQU $00
LEVEL_0E        EQU $0E
LEVEL_11        EQU $11
LEVEL_14        EQU $14

SAVEFILE_SELECT_STATE_FALLING_MARIO EQU 0
SAVEFILE_SELECT_STATE_IDLE          EQU 1
SAVEFILE_SELECT_STATE_WALKING_RIGHT EQU 2
SAVEFILE_SELECT_STATE_WALKING_LEFT  EQU 3
SAVEFILE_SELECT_STATE_TOGGLE_CLEAR  EQU 4
SAVEFILE_SELECT_STATE_ENTERING_SAVE EQU 5
SAVEFILE_SELECT_STATE_BLEW_UP       EQU 6
